version: "3"
services:
  api:
    build: 
      context: .
      args:
        NODE_ENV: development
    ports:
      - "4000:5500"
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    
  


