export const majorBooks: string[] = [
  "Poetry writers",
  "Crime fiction writers",
  "Horror lovers",
  "Romance writers",
  "Young Adult (YA) Literature Fans",
  "Thriller Aficionados",
  "Historical Fiction Writers",
  "Fantasy Enthusiasts",
  "Science Fiction Writers",

  "Pride and Prejudice by Jane Austen",
  "To Kill a Mockingbird by Harper Lee",
  "1984 by George Orwell",
  "The Great Gatsby by F. Scott Fitzgerald",
  "Moby-Dick by Herman Melville",
  "The Catcher in the Rye by J.D. Salinger",
  "War and Peace by Leo Tolstoy",
  "Crime and Punishment by Fyodor Dostoevsky",
  "Jane Eyre by Charlotte Bronte",
  "Wuthering Heights by Emily Bronte",
  "The Lord of the Rings by J.R.R. Tolkien",
  "The Hobbit by J.R.R. Tolkien",
  "Frankenstein by Mary Shelley",
  "The Adventures of Huckleberry Finn by Mark Twain",
  "The Grapes of Wrath by John Steinbeck",
  "Anna Karenina by Leo Tolstoy",
  "The Odyssey by Homer",
  "The Iliad by Homer",
  "One Hundred Years of Solitude by Gabriel Garcia Marquez",
  "Don Quixote by Miguel de Cervantes",
  "The Brothers Karamazov by Fyodor Dostoevsky",
  "Les Misérables by Victor Hugo",
  "The Picture of Dorian Gray by Oscar Wilde",
  "The Canterbury Tales by Geoffrey Chaucer",
  "Dracula by Bram Stoker",
  "Walden by Henry David Thoreau",
  "Siddhartha by Hermann Hesse",
  "The Divine Comedy by Dante Alighieri",
  "The Count of Monte Cristo by Alexandre Dumas",
  "Gone with the Wind by Margaret Mitchell",
  "The Scarlet Letter by Nathaniel Hawthorne",
  "Alice's Adventures in Wonderland by Lewis Carroll",
  "The Adventures of Sherlock Holmes by Arthur Conan Doyle",
  "Anne Frank: The Diary of a Young Girl by Anne Frank",
  "Looking for Alaska by John Green",
  "The Fault in Our Stars by John Green",
  "Paper Towns by John Green",
  "Turtles All the Way Down by John Green",
  "The Secret Garden by Frances Hodgson Burnett",
  "Little Women by Louisa May Alcott",
  "The Secret Life of Bees by Sue Monk Kidd",
  "The Bell Jar by Sylvia Plath",
  "A Tale of Two Cities by Charles Dickens",
  "Great Expectations by Charles Dickens",
  "Sense and Sensibility by Jane Austen",
  "Emma by Jane Austen",
  "Mansfield Park by Jane Austen",
  "Northanger Abbey by Jane Austen",
  "Persuasion by Jane Austen",
];
